# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_location_street_addr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
